; Auto-generated. Do not edit!


(cl:in-package assignment_2_2023-msg)


;//! \htmlinclude PlanningResult.msg.html

(cl:defclass <PlanningResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlanningResult (<PlanningResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlanningResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlanningResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name assignment_2_2023-msg:<PlanningResult> is deprecated: use assignment_2_2023-msg:PlanningResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlanningResult>) ostream)
  "Serializes a message object of type '<PlanningResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlanningResult>) istream)
  "Deserializes a message object of type '<PlanningResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlanningResult>)))
  "Returns string type for a message object of type '<PlanningResult>"
  "assignment_2_2023/PlanningResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlanningResult)))
  "Returns string type for a message object of type 'PlanningResult"
  "assignment_2_2023/PlanningResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlanningResult>)))
  "Returns md5sum for a message object of type '<PlanningResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlanningResult)))
  "Returns md5sum for a message object of type 'PlanningResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlanningResult>)))
  "Returns full string definition for message of type '<PlanningResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlanningResult)))
  "Returns full string definition for message of type 'PlanningResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlanningResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlanningResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PlanningResult
))
