// Generated by gencpp from file robot_description/Position.msg
// DO NOT EDIT!


#ifndef ROBOT_DESCRIPTION_MESSAGE_POSITION_H
#define ROBOT_DESCRIPTION_MESSAGE_POSITION_H

#include <ros/service_traits.h>


#include <robot_description/PositionRequest.h>
#include <robot_description/PositionResponse.h>


namespace robot_description
{

struct Position
{

typedef PositionRequest Request;
typedef PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Position
} // namespace robot_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_description::Position > {
  static const char* value()
  {
    return "2f1d14ba96d90c01d836ab12b368aeb3";
  }

  static const char* value(const ::robot_description::Position&) { return value(); }
};

template<>
struct DataType< ::robot_description::Position > {
  static const char* value()
  {
    return "robot_description/Position";
  }

  static const char* value(const ::robot_description::Position&) { return value(); }
};


// service_traits::MD5Sum< ::robot_description::PositionRequest> should match
// service_traits::MD5Sum< ::robot_description::Position >
template<>
struct MD5Sum< ::robot_description::PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_description::Position >::value();
  }
  static const char* value(const ::robot_description::PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_description::PositionRequest> should match
// service_traits::DataType< ::robot_description::Position >
template<>
struct DataType< ::robot_description::PositionRequest>
{
  static const char* value()
  {
    return DataType< ::robot_description::Position >::value();
  }
  static const char* value(const ::robot_description::PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_description::PositionResponse> should match
// service_traits::MD5Sum< ::robot_description::Position >
template<>
struct MD5Sum< ::robot_description::PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_description::Position >::value();
  }
  static const char* value(const ::robot_description::PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_description::PositionResponse> should match
// service_traits::DataType< ::robot_description::Position >
template<>
struct DataType< ::robot_description::PositionResponse>
{
  static const char* value()
  {
    return DataType< ::robot_description::Position >::value();
  }
  static const char* value(const ::robot_description::PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_DESCRIPTION_MESSAGE_POSITION_H
