// Generated by gencpp from file turtlebot_controller/Velocity.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_CONTROLLER_MESSAGE_VELOCITY_H
#define TURTLEBOT_CONTROLLER_MESSAGE_VELOCITY_H

#include <ros/service_traits.h>


#include <turtlebot_controller/VelocityRequest.h>
#include <turtlebot_controller/VelocityResponse.h>


namespace turtlebot_controller
{

struct Velocity
{

typedef VelocityRequest Request;
typedef VelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Velocity
} // namespace turtlebot_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_controller::Velocity > {
  static const char* value()
  {
    return "9642048b94dbb901a7afb7dca7c2308c";
  }

  static const char* value(const ::turtlebot_controller::Velocity&) { return value(); }
};

template<>
struct DataType< ::turtlebot_controller::Velocity > {
  static const char* value()
  {
    return "turtlebot_controller/Velocity";
  }

  static const char* value(const ::turtlebot_controller::Velocity&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_controller::VelocityRequest> should match
// service_traits::MD5Sum< ::turtlebot_controller::Velocity >
template<>
struct MD5Sum< ::turtlebot_controller::VelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_controller::Velocity >::value();
  }
  static const char* value(const ::turtlebot_controller::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_controller::VelocityRequest> should match
// service_traits::DataType< ::turtlebot_controller::Velocity >
template<>
struct DataType< ::turtlebot_controller::VelocityRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_controller::Velocity >::value();
  }
  static const char* value(const ::turtlebot_controller::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_controller::VelocityResponse> should match
// service_traits::MD5Sum< ::turtlebot_controller::Velocity >
template<>
struct MD5Sum< ::turtlebot_controller::VelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_controller::Velocity >::value();
  }
  static const char* value(const ::turtlebot_controller::VelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_controller::VelocityResponse> should match
// service_traits::DataType< ::turtlebot_controller::Velocity >
template<>
struct DataType< ::turtlebot_controller::VelocityResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_controller::Velocity >::value();
  }
  static const char* value(const ::turtlebot_controller::VelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_CONTROLLER_MESSAGE_VELOCITY_H
