// Generated by gencpp from file assignment_2_2023/AvrgResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_AVRGRESPONSE_H
#define ASSIGNMENT_2_2023_MESSAGE_AVRGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2023
{
template <class ContainerAllocator>
struct AvrgResponse_
{
  typedef AvrgResponse_<ContainerAllocator> Type;

  AvrgResponse_()
    : dis(0.0)
    , speed(0.0)  {
    }
  AvrgResponse_(const ContainerAllocator& _alloc)
    : dis(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _dis_type;
  _dis_type dis;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AvrgResponse_

typedef ::assignment_2_2023::AvrgResponse_<std::allocator<void> > AvrgResponse;

typedef boost::shared_ptr< ::assignment_2_2023::AvrgResponse > AvrgResponsePtr;
typedef boost::shared_ptr< ::assignment_2_2023::AvrgResponse const> AvrgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2023::AvrgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2023::AvrgResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::AvrgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.dis == rhs.dis &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2023::AvrgResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::AvrgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5df81caea40a0fa6af31fa77f59b6d1e";
  }

  static const char* value(const ::assignment_2_2023::AvrgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5df81caea40a0fa6ULL;
  static const uint64_t static_value2 = 0xaf31fa77f59b6d1eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2023/AvrgResponse";
  }

  static const char* value(const ::assignment_2_2023::AvrgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 dis\n"
"float32 speed\n"
"\n"
;
  }

  static const char* value(const ::assignment_2_2023::AvrgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dis);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AvrgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2023::AvrgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2023::AvrgResponse_<ContainerAllocator>& v)
  {
    s << indent << "dis: ";
    Printer<float>::stream(s, indent + "  ", v.dis);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_AVRGRESPONSE_H
