// Generated by gencpp from file assignment_2_2023/Cancelgoal.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_CANCELGOAL_H
#define ASSIGNMENT_2_2023_MESSAGE_CANCELGOAL_H

#include <ros/service_traits.h>


#include <assignment_2_2023/CancelgoalRequest.h>
#include <assignment_2_2023/CancelgoalResponse.h>


namespace assignment_2_2023
{

struct Cancelgoal
{

typedef CancelgoalRequest Request;
typedef CancelgoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Cancelgoal
} // namespace assignment_2_2023


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2023::Cancelgoal > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::assignment_2_2023::Cancelgoal&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2023::Cancelgoal > {
  static const char* value()
  {
    return "assignment_2_2023/Cancelgoal";
  }

  static const char* value(const ::assignment_2_2023::Cancelgoal&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2023::CancelgoalRequest> should match
// service_traits::MD5Sum< ::assignment_2_2023::Cancelgoal >
template<>
struct MD5Sum< ::assignment_2_2023::CancelgoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::Cancelgoal >::value();
  }
  static const char* value(const ::assignment_2_2023::CancelgoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::CancelgoalRequest> should match
// service_traits::DataType< ::assignment_2_2023::Cancelgoal >
template<>
struct DataType< ::assignment_2_2023::CancelgoalRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::Cancelgoal >::value();
  }
  static const char* value(const ::assignment_2_2023::CancelgoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2023::CancelgoalResponse> should match
// service_traits::MD5Sum< ::assignment_2_2023::Cancelgoal >
template<>
struct MD5Sum< ::assignment_2_2023::CancelgoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::Cancelgoal >::value();
  }
  static const char* value(const ::assignment_2_2023::CancelgoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::CancelgoalResponse> should match
// service_traits::DataType< ::assignment_2_2023::Cancelgoal >
template<>
struct DataType< ::assignment_2_2023::CancelgoalResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::Cancelgoal >::value();
  }
  static const char* value(const ::assignment_2_2023::CancelgoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_CANCELGOAL_H
