// Generated by gencpp from file assignment_2_2023/CsrvResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_CSRVRESPONSE_H
#define ASSIGNMENT_2_2023_MESSAGE_CSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2023
{
template <class ContainerAllocator>
struct CsrvResponse_
{
  typedef CsrvResponse_<ContainerAllocator> Type;

  CsrvResponse_()
    : goal_x(0.0)
    , goal_y(0.0)  {
    }
  CsrvResponse_(const ContainerAllocator& _alloc)
    : goal_x(0.0)
    , goal_y(0.0)  {
  (void)_alloc;
    }



   typedef float _goal_x_type;
  _goal_x_type goal_x;

   typedef float _goal_y_type;
  _goal_y_type goal_y;





  typedef boost::shared_ptr< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CsrvResponse_

typedef ::assignment_2_2023::CsrvResponse_<std::allocator<void> > CsrvResponse;

typedef boost::shared_ptr< ::assignment_2_2023::CsrvResponse > CsrvResponsePtr;
typedef boost::shared_ptr< ::assignment_2_2023::CsrvResponse const> CsrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2023::CsrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2023::CsrvResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::CsrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.goal_x == rhs.goal_x &&
    lhs.goal_y == rhs.goal_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2023::CsrvResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2023::CsrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9aa8c2e2b21fc8544d27640eeac21d97";
  }

  static const char* value(const ::assignment_2_2023::CsrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9aa8c2e2b21fc854ULL;
  static const uint64_t static_value2 = 0x4d27640eeac21d97ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2023/CsrvResponse";
  }

  static const char* value(const ::assignment_2_2023::CsrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 goal_x\n"
"float32 goal_y\n"
"\n"
;
  }

  static const char* value(const ::assignment_2_2023::CsrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_x);
      stream.next(m.goal_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CsrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2023::CsrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2023::CsrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "goal_x: ";
    Printer<float>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<float>::stream(s, indent + "  ", v.goal_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_CSRVRESPONSE_H
