// Generated by gencpp from file assignment_2_2023/Csrv.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_CSRV_H
#define ASSIGNMENT_2_2023_MESSAGE_CSRV_H

#include <ros/service_traits.h>


#include <assignment_2_2023/CsrvRequest.h>
#include <assignment_2_2023/CsrvResponse.h>


namespace assignment_2_2023
{

struct Csrv
{

typedef CsrvRequest Request;
typedef CsrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Csrv
} // namespace assignment_2_2023


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2023::Csrv > {
  static const char* value()
  {
    return "9aa8c2e2b21fc8544d27640eeac21d97";
  }

  static const char* value(const ::assignment_2_2023::Csrv&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2023::Csrv > {
  static const char* value()
  {
    return "assignment_2_2023/Csrv";
  }

  static const char* value(const ::assignment_2_2023::Csrv&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2023::CsrvRequest> should match
// service_traits::MD5Sum< ::assignment_2_2023::Csrv >
template<>
struct MD5Sum< ::assignment_2_2023::CsrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::Csrv >::value();
  }
  static const char* value(const ::assignment_2_2023::CsrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::CsrvRequest> should match
// service_traits::DataType< ::assignment_2_2023::Csrv >
template<>
struct DataType< ::assignment_2_2023::CsrvRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::Csrv >::value();
  }
  static const char* value(const ::assignment_2_2023::CsrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2023::CsrvResponse> should match
// service_traits::MD5Sum< ::assignment_2_2023::Csrv >
template<>
struct MD5Sum< ::assignment_2_2023::CsrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2023::Csrv >::value();
  }
  static const char* value(const ::assignment_2_2023::CsrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2023::CsrvResponse> should match
// service_traits::DataType< ::assignment_2_2023::Csrv >
template<>
struct DataType< ::assignment_2_2023::CsrvResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2023::Csrv >::value();
  }
  static const char* value(const ::assignment_2_2023::CsrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_CSRV_H
