// Generated by gencpp from file assignment_2_2023/Custom.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2023_MESSAGE_CUSTOM_H
#define ASSIGNMENT_2_2023_MESSAGE_CUSTOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2023
{
template <class ContainerAllocator>
struct Custom_
{
  typedef Custom_<ContainerAllocator> Type;

  Custom_()
    : posx(0.0)
    , posy(0.0)
    , velx(0.0)
    , vely(0.0)  {
    }
  Custom_(const ContainerAllocator& _alloc)
    : posx(0.0)
    , posy(0.0)
    , velx(0.0)
    , vely(0.0)  {
  (void)_alloc;
    }



   typedef float _posx_type;
  _posx_type posx;

   typedef float _posy_type;
  _posy_type posy;

   typedef float _velx_type;
  _velx_type velx;

   typedef float _vely_type;
  _vely_type vely;





  typedef boost::shared_ptr< ::assignment_2_2023::Custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2023::Custom_<ContainerAllocator> const> ConstPtr;

}; // struct Custom_

typedef ::assignment_2_2023::Custom_<std::allocator<void> > Custom;

typedef boost::shared_ptr< ::assignment_2_2023::Custom > CustomPtr;
typedef boost::shared_ptr< ::assignment_2_2023::Custom const> CustomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2023::Custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2023::Custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2023::Custom_<ContainerAllocator1> & lhs, const ::assignment_2_2023::Custom_<ContainerAllocator2> & rhs)
{
  return lhs.posx == rhs.posx &&
    lhs.posy == rhs.posy &&
    lhs.velx == rhs.velx &&
    lhs.vely == rhs.vely;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2023::Custom_<ContainerAllocator1> & lhs, const ::assignment_2_2023::Custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2023

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::Custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2023::Custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::Custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2023::Custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::Custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2023::Custom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2023::Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96d26a4348b9e22969093b954705dc9f";
  }

  static const char* value(const ::assignment_2_2023::Custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96d26a4348b9e229ULL;
  static const uint64_t static_value2 = 0x69093b954705dc9fULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2023::Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2023/Custom";
  }

  static const char* value(const ::assignment_2_2023::Custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2023::Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 posx\n"
"float32 posy\n"
"float32 velx\n"
"float32 vely\n"
;
  }

  static const char* value(const ::assignment_2_2023::Custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2023::Custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posx);
      stream.next(m.posy);
      stream.next(m.velx);
      stream.next(m.vely);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2023::Custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2023::Custom_<ContainerAllocator>& v)
  {
    s << indent << "posx: ";
    Printer<float>::stream(s, indent + "  ", v.posx);
    s << indent << "posy: ";
    Printer<float>::stream(s, indent + "  ", v.posy);
    s << indent << "velx: ";
    Printer<float>::stream(s, indent + "  ", v.velx);
    s << indent << "vely: ";
    Printer<float>::stream(s, indent + "  ", v.vely);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2023_MESSAGE_CUSTOM_H
