(cl:defpackage assignment_2_2023-srv
  (:use )
  (:export
   "AVRG"
   "<AVRG-REQUEST>"
   "AVRG-REQUEST"
   "<AVRG-RESPONSE>"
   "AVRG-RESPONSE"
   "CANCELGOAL"
   "<CANCELGOAL-REQUEST>"
   "CANCELGOAL-REQUEST"
   "<CANCELGOAL-RESPONSE>"
   "CANCELGOAL-RESPONSE"
   "CSRV"
   "<CSRV-REQUEST>"
   "CSRV-REQUEST"
   "<CSRV-RESPONSE>"
   "CSRV-RESPONSE"
  ))

